In [233]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [234]:
iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')

In [235]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [236]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [237]:
feat_cols = [sepal_length, sepal_width, petal_length, petal_width]

In [238]:
sepal_length = tf.feature_column.numeric_column('sepal_length')
sepal_width = tf.feature_column.numeric_column('sepal_width')
petal_length = tf.feature_column.numeric_column('petal_length')
petal_width = tf.feature_column.numeric_column('petal_width')

In [239]:
df = iris.groupby('species')['sepal_width'].nunique()

In [240]:
print(df)

species
setosa        16
versicolor    14
virginica     13
Name: sepal_width, dtype: int64

In [241]:
iris['species']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
5         setosa
6         setosa
7         setosa
8         setosa
9         setosa
10        setosa
11        setosa
12        setosa
13        setosa
14        setosa
15        setosa
16        setosa
17        setosa
18        setosa
19        setosa
20        setosa
21        setosa
22        setosa
23        setosa
24        setosa
25        setosa
26        setosa
27        setosa
28        setosa
29        setosa
         ...
120    virginica
121    virginica
122    virginica
123    virginica
124    virginica
125    virginica
126    virginica
127    virginica
128    virginica
129    virginica
130    virginica
131    virginica
132    virginica
133    virginica
134    virginica
135    virginica
136    virginica
137    virginica
138    virginica
139    virginica
140    virginica
141    virginica
142    virginica
143    virginica
144    virginica
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [242]:
iris.dropna()

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [244]:
#iris['species'] = iris['species'].map({'setosa': 1, 'versicolor': 2, 'virginia': 3})
iris['species'] = iris['species'].rank(method='dense', ascending=False).astype(int)

In [255]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        3
1           4.9          3.0           1.4          0.2        3
2           4.7          3.2           1.3          0.2        3
3           4.6          3.1           1.5          0.2        3
4           5.0          3.6           1.4          0.2        3

In [256]:
df = iris.groupby('species')['sepal_width'].nunique()

In [257]:
print(df)

species
1    13
2    14
3    16
Name: sepal_width, dtype: int64

In [246]:
labels = iris['species']

In [247]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        3
1           4.9          3.0           1.4          0.2        3
2           4.7          3.2           1.3          0.2        3
3           4.6          3.1           1.5          0.2        3
4           5.0          3.6           1.4          0.2        3

In [248]:
x_data = iris.drop('species', axis=1)

In [249]:
x_data.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [250]:
from sklearn.model_selection import train_test_split

In [251]:
X_train, X_test, y_train, y_test = train_test_split(x_data, labels, test_size=0.3,random_state=101)

### tensor flow

In [252]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train, y=y_train, batch_size=20, num_epochs=5000, shuffle=True)

In [258]:
model = tf.estimator.DNNClassifier(hidden_units=[10,20,20,10], feature_columns=feat_cols, n_classes=4)

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\mojiway\AppData\Local\Temp\tmph9hc8744
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\mojiway\\AppData\\Local\\Temp\\tmph9hc8744', '_tf_random_seed': 1, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100}

In [259]:
model.train(input_fn= input_func, steps=5000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into C:\Users\mojiway\AppData\Local\Temp\tmph9hc8744\model.ckpt.
INFO:tensorflow:loss = 58.25579, step = 1
INFO:tensorflow:global_step/sec: 569.7
INFO:tensorflow:loss = 3.3936174, step = 101 (0.177 sec)
INFO:tensorflow:global_step/sec: 651.091
INFO:tensorflow:loss = 1.2113616, step = 201 (0.156 sec)
INFO:tensorflow:global_step/sec: 672.934
INFO:tensorflow:loss = 5.122657, step = 301 (0.149 sec)
INFO:tensorflow:global_step/sec: 672.846
INFO:tensorflow:loss = 3.1918514, step = 401 (0.149 sec)
INFO:tensorflow:global_step/sec: 644.769
INFO:tensorflow:loss = 3.020607, step = 501 (0.155 sec)
INFO:tensorflow:global_step/sec: 657.44
INFO:tensorflow:loss = 1.3816166, step = 601 (0.150 sec)
INFO:tensorflow:global_step/sec: 696.299
INFO:tensorflow:loss = 1.9789827, step = 701 (0.146 sec)
INFO:tensorflow:global_step/sec: 527.721
INFO:tensorflow:loss = 1.3200741, step = 801 (0.194 sec)
INFO:tensorflow:global_step/sec: 550.927
INFO:tensorflow:loss = 1.1366901, step = 901 (0.176 sec)
INFO:tensorflow:global_step/sec: 579.582
INFO:tensorflow:loss = 1.4796222, step = 1001 (0.181 sec)
INFO:tensorflow:global_step/sec: 527.724
INFO:tensorflow:loss = 2.5579834, step = 1101 (0.183 sec)
INFO:tensorflow:global_step/sec: 550.92
INFO:tensorflow:loss = 0.86351395, step = 1201 (0.181 sec)
INFO:tensorflow:global_step/sec: 641.202
INFO:tensorflow:loss = 1.4446316, step = 1301 (0.160 sec)
INFO:tensorflow:global_step/sec: 460.965
INFO:tensorflow:loss = 6.86566, step = 1401 (0.215 sec)
INFO:tensorflow:global_step/sec: 553.978
INFO:tensorflow:loss = 0.1169123, step = 1501 (0.189 sec)
INFO:tensorflow:global_step/sec: 498.843
INFO:tensorflow:loss = 0.88482416, step = 1601 (0.190 sec)
INFO:tensorflow:global_step/sec: 593.3
INFO:tensorflow:loss = 1.5210798, step = 1701 (0.167 sec)
INFO:tensorflow:global_step/sec: 537.594
INFO:tensorflow:loss = 1.1028919, step = 1801 (0.192 sec)
INFO:tensorflow:global_step/sec: 655.343
INFO:tensorflow:loss = 0.99552536, step = 1901 (0.149 sec)
INFO:tensorflow:global_step/sec: 646.886
INFO:tensorflow:loss = 0.047022626, step = 2001 (0.156 sec)
INFO:tensorflow:global_step/sec: 538.563
INFO:tensorflow:loss = 0.034282178, step = 2101 (0.190 sec)
INFO:tensorflow:global_step/sec: 579.589
INFO:tensorflow:loss = 1.2449777, step = 2201 (0.168 sec)
INFO:tensorflow:global_step/sec: 655.344
INFO:tensorflow:loss = 1.0045618, step = 2301 (0.157 sec)
INFO:tensorflow:global_step/sec: 397.887
INFO:tensorflow:loss = 0.4400552, step = 2401 (0.255 sec)
INFO:tensorflow:global_step/sec: 386.37
INFO:tensorflow:loss = 0.86546934, step = 2501 (0.254 sec)
INFO:tensorflow:global_step/sec: 381.245
INFO:tensorflow:loss = 0.058359645, step = 2601 (0.261 sec)
INFO:tensorflow:global_step/sec: 445.635
INFO:tensorflow:loss = 1.4322664, step = 2701 (0.228 sec)
INFO:tensorflow:global_step/sec: 424.861
INFO:tensorflow:loss = 0.79025924, step = 2801 (0.231 sec)
INFO:tensorflow:global_step/sec: 408.4
INFO:tensorflow:loss = 0.4297107, step = 2901 (0.247 sec)
INFO:tensorflow:global_step/sec: 462.065
INFO:tensorflow:loss = 3.4264655, step = 3001 (0.212 sec)
INFO:tensorflow:global_step/sec: 607.682
INFO:tensorflow:loss = 0.11585448, step = 3101 (0.165 sec)
INFO:tensorflow:global_step/sec: 493.927
INFO:tensorflow:loss = 1.5329338, step = 3201 (0.202 sec)
INFO:tensorflow:global_step/sec: 559.876
INFO:tensorflow:loss = 1.0880305, step = 3301 (0.184 sec)
INFO:tensorflow:global_step/sec: 572.958
INFO:tensorflow:loss = 3.687843, step = 3401 (0.171 sec)
INFO:tensorflow:global_step/sec: 686.424
INFO:tensorflow:loss = 1.1336617, step = 3501 (0.144 sec)
INFO:tensorflow:global_step/sec: 622.781
INFO:tensorflow:loss = 0.884294, step = 3601 (0.161 sec)
INFO:tensorflow:global_step/sec: 579.579
INFO:tensorflow:loss = 1.0259143, step = 3701 (0.173 sec)
INFO:tensorflow:global_step/sec: 664.024
INFO:tensorflow:loss = 2.103626, step = 3801 (0.151 sec)
INFO:tensorflow:global_step/sec: 655.344
INFO:tensorflow:loss = 0.88049674, step = 3901 (0.154 sec)
INFO:tensorflow:global_step/sec: 624.668
INFO:tensorflow:loss = 0.43224144, step = 4001 (0.162 sec)
INFO:tensorflow:global_step/sec: 643.109
INFO:tensorflow:loss = 0.8913141, step = 4101 (0.153 sec)
INFO:tensorflow:global_step/sec: 604.024
INFO:tensorflow:loss = 0.40431723, step = 4201 (0.167 sec)
INFO:tensorflow:global_step/sec: 667.781
INFO:tensorflow:loss = 2.4388564, step = 4301 (0.150 sec)
INFO:tensorflow:global_step/sec: 636.57
INFO:tensorflow:loss = 0.4282743, step = 4401 (0.158 sec)
INFO:tensorflow:global_step/sec: 634.604
INFO:tensorflow:loss = 0.40112314, step = 4501 (0.158 sec)
INFO:tensorflow:global_step/sec: 651.088
INFO:tensorflow:loss = 0.2929433, step = 4601 (0.154 sec)
INFO:tensorflow:global_step/sec: 607.652
INFO:tensorflow:loss = 0.16723134, step = 4701 (0.168 sec)
INFO:tensorflow:global_step/sec: 477.482
INFO:tensorflow:loss = 0.9228573, step = 4801 (0.204 sec)
INFO:tensorflow:global_step/sec: 536.19
INFO:tensorflow:loss = 5.326221, step = 4901 (0.187 sec)
INFO:tensorflow:Saving checkpoints for 5000 into C:\Users\mojiway\AppData\Local\Temp\tmph9hc8744\model.ckpt.
INFO:tensorflow:Loss for final step: 2.093959.

In [260]:
eval_input_func = tf.estimator.inputs.pandas_input_fn(x=X_test, y=y_test, batch_size=10, num_epochs=1, shuffle=False)

In [261]:
model.evaluate(eval_input_func)

INFO:tensorflow:Starting evaluation at 2019-03-14-02:28:51
INFO:tensorflow:Restoring parameters from C:\Users\mojiway\AppData\Local\Temp\tmph9hc8744\model.ckpt-5000
INFO:tensorflow:Finished evaluation at 2019-03-14-02:28:52
INFO:tensorflow:Saving dict for global step 5000: accuracy = 1.0, average_loss = 0.030483125, global_step = 5000, loss = 0.2743481

{'accuracy': 1.0,
 'average_loss': 0.030483125,
 'loss': 0.2743481,
 'global_step': 5000}

In [262]:
pred_input_func = tf.estimator.inputs.pandas_input_fn(x = X_test, batch_size=10, num_epochs=1, shuffle=False)

In [263]:

predictions = model.predict(pred_input_func)

In [266]:
list(predictions)

INFO:tensorflow:Restoring parameters from C:\Users\mojiway\AppData\Local\Temp\tmph9hc8744\model.ckpt-5000

[{'logits': array([ -9.607378 , -44.711903 ,  -1.5995011,   9.260335 ], dtype=float32),
  'probabilities': array([6.3951044e-09, 3.6320107e-24, 1.9214300e-05, 9.9998081e-01],
        dtype=float32),
  'class_ids': array([3], dtype=int64),
  'classes': array([b'3'], dtype=object)},
 {'logits': array([ -8.97405  , -41.0239   ,  -1.3591859,   8.521087 ], dtype=float32),
  'probabilities': array([2.5231127e-08, 3.0399291e-22, 5.1171697e-05, 9.9994886e-01],
        dtype=float32),
  'class_ids': array([3], dtype=int64),
  'classes': array([b'3'], dtype=object)},
 {'logits': array([ -7.8401346, -34.457306 ,  -0.9284872,   7.161206 ], dtype=float32),
  'probabilities': array([3.0539869e-07, 8.4173806e-19, 3.0658979e-04, 9.9969316e-01],
        dtype=float32),
  'class_ids': array([3], dtype=int64),
  'classes': array([b'3'], dtype=object)},
 {'logits': array([-10.648621 ,   6.138831 ,   4.5749063, -19.49893  ], dtype=float32),
  'probabilities': array([4.2341210e-08, 8.2691586e-01, 1.7308420e-01, 6.0690897e-12],
        dtype=float32),
  'class_ids': array([1], dtype=int64),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([-10.098436 ,  -6.1185694,   3.084345 , -11.452203 ], dtype=float32),
  'probabilities': array([1.88254808e-06, 1.00734986e-04, 9.99896884e-01, 4.86197564e-07],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([ -8.982656 ,   6.279063 ,   4.0189238, -17.250948 ], dtype=float32),
  'probabilities': array([2.1321536e-07, 9.0552139e-01, 9.4478421e-02, 5.4694683e-11],
        dtype=float32),
  'class_ids': array([1], dtype=int64),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([ -8.805819 ,   2.9666798,   3.5937903, -14.774948 ], dtype=float32),
  'probabilities': array([2.685680e-06, 3.481651e-01, 6.518323e-01, 6.865849e-09],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([ -8.051338  ,  -0.71710366,   2.9451714 , -11.448995  ],
        dtype=float32),
  'probabilities': array([1.6340295e-05, 2.5030956e-02, 9.7495210e-01, 5.4660853e-07],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([ -8.731862,   8.946243,   4.241981, -18.908297], dtype=float32),
  'probabilities': array([2.0824823e-08, 9.9102473e-01, 8.9753084e-03, 7.9252235e-13],
        dtype=float32),
  'class_ids': array([1], dtype=int64),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([ -7.904452  , -35.03321   ,  -0.98866296,   7.2890935 ],
        dtype=float32),
  'probabilities': array([2.5200933e-07, 4.1643436e-19, 2.5404195e-04, 9.9974567e-01],
        dtype=float32),
  'class_ids': array([3], dtype=int64),
  'classes': array([b'3'], dtype=object)},
 {'logits': array([ -9.186266 ,   8.291857 ,   4.3209457, -19.057863 ], dtype=float32),
  'probabilities': array([2.5190385e-08, 9.8149270e-01, 1.8507268e-02, 1.3003331e-12],
        dtype=float32),
  'class_ids': array([1], dtype=int64),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([ -9.365295 , -43.75544  ,  -1.5830731,   9.062899 ], dtype=float32),
  'probabilities': array([9.9249124e-09, 1.1515361e-23, 2.3795950e-05, 9.9997616e-01],
        dtype=float32),
  'class_ids': array([3], dtype=int64),
  'classes': array([b'3'], dtype=object)},
 {'logits': array([ -8.391172 , -36.983604 ,  -1.0233666,   7.6720643], dtype=float32),
  'probabilities': array([1.0562152e-07, 4.0384631e-20, 1.6732070e-04, 9.9983251e-01],
        dtype=float32),
  'class_ids': array([3], dtype=int64),
  'classes': array([b'3'], dtype=object)},
 {'logits': array([-10.744478,  14.042552,   5.591834, -25.743258], dtype=float32),
  'probabilities': array([1.7180554e-11, 9.9978632e-01, 2.1370122e-04, 5.2619908e-18],
        dtype=float32),
  'class_ids': array([1], dtype=int64),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([ -8.930019 ,   5.6455526,   3.9280293, -16.697828 ], dtype=float32),
  'probabilities': array([3.9646756e-07, 8.4780926e-01, 1.5219039e-01, 1.6776119e-10],
        dtype=float32),
  'class_ids': array([1], dtype=int64),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([ -9.280231 ,  -6.1689296,   2.7948475, -10.16255  ], dtype=float32),
  'probabilities': array([5.6990275e-06, 1.2794456e-04, 9.9986398e-01, 2.3583850e-06],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([-8.447598 , -6.849501 ,  2.4181304, -8.551557 ], dtype=float32),
  'probabilities': array([1.9099298e-05, 9.4419564e-05, 9.9986935e-01, 1.7213490e-05],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([-8.5610075, -5.107725 ,  2.6470795, -9.71894  ], dtype=float32),
  'probabilities': array([1.3558005e-05, 4.2848659e-04, 9.9955362e-01, 4.2590441e-06],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([ -7.728173 , -35.34714  ,  -1.1490995,   7.3632894], dtype=float32),
  'probabilities': array([2.7910903e-07, 2.8249353e-19, 2.0092269e-04, 9.9979883e-01],
        dtype=float32),
  'class_ids': array([3], dtype=int64),
  'classes': array([b'3'], dtype=object)},
 {'logits': array([ -9.290033 ,   8.84124  ,   4.4274263, -19.610973 ], dtype=float32),
  'probabilities': array([1.3196563e-08, 9.8803598e-01, 1.1964041e-02, 4.3464383e-13],
        dtype=float32),
  'class_ids': array([1], dtype=int64),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([-8.126055 , -5.453587 ,  2.4717274, -8.79276  ], dtype=float32),
  'probabilities': array([2.4961362e-05, 3.6133185e-04, 9.9960083e-01, 1.2815098e-05],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([ -8.928057 , -40.449734 ,  -1.2907524,   8.409858 ], dtype=float32),
  'probabilities': array([2.9526584e-08, 6.0328427e-22, 6.1242361e-05, 9.9993873e-01],
        dtype=float32),
  'class_ids': array([3], dtype=int64),
  'classes': array([b'3'], dtype=object)},
 {'logits': array([ -8.446158 ,  -0.7544133,   3.075967 , -12.044856 ], dtype=float32),
  'probabilities': array([9.6978702e-06, 2.1240203e-02, 9.7874993e-01, 2.6532723e-07],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([ -9.616203 ,  -6.9346375,   2.8284698, -10.242682 ], dtype=float32),
  'probabilities': array([3.9383954e-06, 5.7531899e-05, 9.9993634e-01, 2.1049573e-06],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([ -9.090127 ,  -5.602034 ,   2.7859943, -10.212758 ], dtype=float32),
  'probabilities': array([6.9528546e-06, 2.2752171e-04, 9.9976331e-01, 2.2626150e-06],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([-8.165888 , -9.921017 ,  1.9954166, -6.3254213], dtype=float32),
  'probabilities': array([3.8625680e-05, 6.6777998e-06, 9.9971133e-01, 2.4332157e-04],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([-7.4342628, -8.643506 ,  1.8873029, -5.895496 ], dtype=float32),
  'probabilities': array([8.9426045e-05, 2.6686777e-05, 9.9946719e-01, 4.1662180e-04],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([ -8.086107 ,  10.108921 ,   4.1666994, -18.912748 ], dtype=float32),
  'probabilities': array([1.2498577e-08, 9.9738067e-01, 2.6193098e-03, 2.4826191e-13],
        dtype=float32),
  'class_ids': array([1], dtype=int64),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([ -7.915559 , -34.604794 ,  -0.9068271,   7.182964 ], dtype=float32),
  'probabilities': array([2.7711616e-07, 7.1067998e-19, 3.0655964e-04, 9.9969316e-01],
        dtype=float32),
  'class_ids': array([3], dtype=int64),
  'classes': array([b'3'], dtype=object)},
 {'logits': array([ -6.737407 , -28.727707 ,  -0.6249157,   5.957445 ], dtype=float32),
  'probabilities': array([3.0626209e-06, 8.6263778e-16, 1.3826581e-03, 9.9861431e-01],
        dtype=float32),
  'class_ids': array([3], dtype=int64),
  'classes': array([b'3'], dtype=object)},
 {'logits': array([ -9.201264 ,  11.733543 ,   4.7568216, -21.754526 ], dtype=float32),
  'probabilities': array([8.0858137e-10, 9.9906749e-01, 9.3248760e-04, 2.8570106e-15],
        dtype=float32),
  'class_ids': array([1], dtype=int64),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([ -8.121181 ,  -1.9774029,   2.8356402, -10.823104 ], dtype=float32),
  'probabilities': array([1.7297833e-05, 8.0575002e-03, 9.9192399e-01, 1.1602760e-06],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([ -9.488758,   8.575502,   4.45998 , -19.696632], dtype=float32),
  'probabilities': array([1.4052772e-08, 9.8394459e-01, 1.6055431e-02, 5.1824907e-13],
        dtype=float32),
  'class_ids': array([1], dtype=int64),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([-8.500977 , -7.2557893,  2.4055882, -8.344146 ], dtype=float32),
  'probabilities': array([1.8335561e-05, 6.3690160e-05, 9.9989653e-01, 2.1448895e-05],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([ -9.454074 ,  10.347492 ,   4.6503916, -20.98758  ], dtype=float32),
  'probabilities': array([2.5051503e-09, 9.9665558e-01, 3.3444578e-03, 2.4541235e-14],
        dtype=float32),
  'class_ids': array([1], dtype=int64),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([ -8.687079 ,  -1.2366903,   3.1051607, -12.150083 ], dtype=float32),
  'probabilities': array([7.4658119e-06, 1.2845169e-02, 9.8714709e-01, 2.3394506e-07],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([ -9.70373  ,  -2.7995799,   3.2978556, -12.783087 ], dtype=float32),
  'probabilities': array([2.2516811e-06, 2.2435766e-03, 9.9775404e-01, 1.0355213e-07],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([ -8.638523 ,  -4.044244 ,   2.7862883, -10.460422 ], dtype=float32),
  'probabilities': array([1.09092025e-05, 1.07910368e-03, 9.98908162e-01, 1.76421941e-06],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([ -8.394952 ,  -2.6196568,   2.8581393, -10.890351 ], dtype=float32),
  'probabilities': array([1.2913018e-05, 4.1610831e-03, 9.9582493e-01, 1.0648527e-06],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([-10.342657,  13.079571,   5.296814, -24.335678], dtype=float32),
  'probabilities': array([6.724728e-11, 9.995833e-01, 4.166877e-04, 5.630966e-17],
        dtype=float32),
  'class_ids': array([1], dtype=int64),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([ -8.46833  , -38.158314 ,  -1.1800892,   7.943003 ], dtype=float32),
  'probabilities': array([7.45763629e-08, 9.51490430e-21, 1.09104774e-04, 9.99890804e-01],
        dtype=float32),
  'class_ids': array([3], dtype=int64),
  'classes': array([b'3'], dtype=object)},
 {'logits': array([ -8.353544 , -39.664486 ,  -1.4988465,   8.220169 ], dtype=float32),
  'probabilities': array([6.3401806e-08, 1.5993091e-21, 6.0125571e-05, 9.9993980e-01],
        dtype=float32),
  'class_ids': array([3], dtype=int64),
  'classes': array([b'3'], dtype=object)},
 {'logits': array([ -7.8869467, -35.11277  ,  -1.0135702,   7.311684 ], dtype=float32),
  'probabilities': array([2.5073385e-07, 3.7600056e-19, 2.4226049e-04, 9.9975747e-01],
        dtype=float32),
  'class_ids': array([3], dtype=int64),
  'classes': array([b'3'], dtype=object)},
 {'logits': array([ -9.682815 ,   2.9051673,   3.8931675, -16.083647 ], dtype=float32),
  'probabilities': array([9.2591245e-07, 2.7130702e-01, 7.2869205e-01, 1.5371768e-09],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([ -8.514937 ,  -0.4251873,   3.1233451, -12.393718 ], dtype=float32),
  'probabilities': array([8.5750617e-06, 2.7962185e-02, 9.7202897e-01, 1.7729819e-07],
        dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)}]

In [272]:
(y_test)

33     3
16     3
43     3
129    1
50     2
123    1
68     2
53     2
146    1
1      3
147    1
32     3
31     3
122    1
127    1
74     2
88     2
96     2
42     3
134    1
80     2
48     3
90     2
65     2
97     2
64     2
93     2
114    1
25     3
41     3
104    1
89     2
116    1
82     2
112    1
55     2
86     2
61     2
94     2
135    1
21     3
22     3
29     3
77     2
66     2
Name: species, dtype: int32